name: nepali_date_picker
description: Material and Cupertino Styled Date Picker, Date Range Picker and Calendar with Bikram Sambat(Nepali) Support.
version: 5.2.0
homepage: https://github.com/sarbagyastha/nepali_date_picker

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  nepali_utils: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
